cat > argocd-app.yaml << EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gce-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Arsenet7/gce-argocd.git
    targetRevision: main
    path: gce-app
  destination:
    server: https://kubernetes.default.svc
    namespace: s6arsene
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
EOF